# This job template makes it easy to create a job that depends on ROCm
apiVersion: batch/v1
kind: Job
metadata:
  # Change this name with something specific to you (aka include your username)
  name: rocm-test-job

# This is the pod spec that starts a rocm container using the latest tensorflow
# image that prebundles ROCm. Feel free to change the args or further customize
# the command to curate for your use case.
spec:
  template:
    spec:
      nodeSelector:
        dev: "true"
      containers:
      - name: rocm-test-container
        image: rocm/tensorflow:latest
        command: ["/bin/bash", "-c"]
        args:
        - |
          rocminfo && echo "ROCm is working!" || echo "ROCm is not working!";
        # This can be modified is more than 1 gpu is needed.
        resources:
          limits:
            amd.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 0
