apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: arc-runners  # Ensure it's in the arc-runners namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "local-storage"