---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: head-node-labeler # Service account that is used to dynamically update head node IP

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-updater # Role that is used for service account
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-updater-binding # Binds role to the service account, so it has neccesary permissions
subjects:
  - kind: ServiceAccount
    name: head-node-labeler
roleRef:
  kind: Role
  name: configmap-updater
  apiGroup: rbac.authorization.k8s.io
