apiVersion: v1
kind: Pod
metadata:
  name: interactive-8gpu-pod
  labels:
    app: interactive-8gpu
spec:
  containers:
  - name: sglang
    image: lmsysorg/sglang:v0.4.8.post1-rocm630
    command: ["sleep"]
    args: ["infinity"]
    resources:
      limits:
        amd.com/gpu: 8
    stdin: true
    tty: true
  restartPolicy: Never
