apiVersion: v1
kind: Pod
metadata:
  name: interactive-jupyter
spec:
  restartPolicy: Always
  containers:
    - name: interactive-shell
      image: ghcr.io/saienduri/rocm-dev:main
      command: ["/bin/bash", "-c", "pip install jupyter && jupyter notebook --ip=0.0.0.0 --port=5000 --allow-root --NotebookApp.token='' --NotebookApp.password='' && tail -f /dev/null"]
      tty: true
      stdin: true
      resources:
        limits:
          amd.com/gpu: 1 
