apiVersion: v1
kind: Pod
metadata:
  name: interactive-vscode
spec:
  restartPolicy: Always
  containers:
    - name: interactive-shell
      image: ghcr.io/saienduri/rocm-dev:main
      command: ["/bin/bash", "-c", "curl -fsSL https://code-server.dev/install.sh | sh && PASSWORD='test' code-server --port 9000 --auth password && tail -f /dev/null"]
      tty: true
      stdin: true
      resources:
        limits:
          amd.com/gpu: 1
 
